#pragma checksum "..\..\..\ClientForm.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "61F8DE8D2B1A5FC6259A7FB96A4E43BEE0AA240F"
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WpfApp1 {
    
    
    /// <summary>
    /// ClientForm
    /// </summary>
    public partial class ClientForm : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker checkInDatePicker;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker checkOutDatePicker;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox firstNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox lastNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox patronymicTextBox;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox numOfGuestsTextBox;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox roomNumberTextBox;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox passportDataTextBox;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox roomPriceTextBox;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox clientCodeTextBox;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox roomLevelTextBox;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\ClientForm.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button addButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp;component/clientform.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\ClientForm.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.checkInDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 2:
            this.checkOutDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 3:
            this.firstNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.lastNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.patronymicTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.numOfGuestsTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.roomNumberTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.passportDataTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.roomPriceTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.clientCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.roomLevelTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.addButton = ((System.Windows.Controls.Button)(target));
            
            #line 55 "..\..\..\ClientForm.xaml"
            this.addButton.Click += new System.Windows.RoutedEventHandler(this.AddButton_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

